FROM ubuntu:20.04 AS mrd_converter
CMD nvidia-smi

LABEL maintainer="Marten Veldmann (marten.veldmann@dzne.de)"

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --quiet \
    && apt-get install --no-install-recommends --no-install-suggests --yes \
       wget apt-utils apt-transport-https gnupg2 python3-dev python3-pip ca-certificates libhdf5-serial-dev h5utils \
       libfftw3-dev git build-essential gfortran liblapacke-dev libpng-dev libopenblas-dev libboost-all-dev libxml2-dev libxslt1-dev libssl-dev curl

RUN  apt-get update --quiet \
     && apt-get dist-upgrade --yes \
     && apt-get install --no-install-recommends --no-install-suggests --yes \
        ca-certificates nano git gcc python3 python3-pip h5utils libxslt1.1 libfftw3-3 liblapacke libhdf5-dev openmpi-bin libatomic1 \
     && pip3 install --no-cache-dir pyxb h5py intel-openmp scipy scikit-image

# Install Latest CMake
RUN  apt install software-properties-common --no-install-recommends --no-install-suggests --yes \
     && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null \
     && apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main' \
     && apt update \
     && apt install cmake --no-install-recommends --no-install-suggests --yes

# Install mkl
COPY ./mkl.sh /tmp/
RUN /tmp/mkl.sh

RUN  mkdir -p /opt/code

RUN  cd /opt/code \
     && git clone -b pulseq https://github.com/pehses/python-ismrmrd-server.git

# ISMRMRD library
RUN cd /opt/code \
    && git clone https://github.com/ismrmrd/ismrmrd.git \
    && cd ismrmrd \
    && mkdir build \
    && cd build \
    && cmake ../ \
    && make -j $(nproc) \
    && make install

# siemens_to_ismrmrd converter
RUN cd /opt/code \
    && git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git \
    && cd siemens_to_ismrmrd \
    && cp /opt/code/python-ismrmrd-server/parameter_maps/* parameter_maps/ \
    && mkdir build \
    && cd build \
    && cmake ../ \
    && make -j $(nproc) \
    && make install

### Dependencies for PowerGrid ###

# Download and install NVIDIA HPC SDK
RUN  wget https://developer.download.nvidia.com/hpc-sdk/20.11/nvhpc-20-11_20.11_amd64.deb \
     https://developer.download.nvidia.com/hpc-sdk/20.11/nvhpc-2020_20.11_amd64.deb \
     && apt-get install ./nvhpc-20-11_20.11_amd64.deb ./nvhpc-2020_20.11_amd64.deb

# Handle NVIDIA HPC SDK specific stuff
ENV NVARCH=Linux_x86_64
ENV NVCOMPILERS=/opt/nvidia/hpc_sdk
ENV NVSDKVER=20.11
ENV CUDA_PATH="${NVCOMPILERS}/${NVARCH}/${NVSDKVER}/cuda"
ENV MANPATH="${MANPATH}:${NVCOMPILERS}/${NVARCH}/20.11/compilers/man"
ENV LD_LIBRARY_PATH="${CUDA_PATH}/lib64:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/20.11/compilers/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/2020/compilers/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/20.11/math_libs/lib64:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/2020/math_libs/lib64:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/mpi/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/2020/comm_libs/mpi/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/nccl/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/2020/comm_libs/nccl/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/nvshmem/lib:${LD_LIBRARY_PATH}"
ENV LD_LIBRARY_PATH="${NVCOMPILERS}/${NVARCH}/2020/comm_libs/nvshmem/lib:${LD_LIBRARY_PATH}"
ENV OPAL_PREFIX="${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/mpi/"
ENV PATH="${NVCOMPILERS}/${NVARCH}/20.11/compilers/bin:${PATH}"
ENV PATH="${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/mpi/bin:${PATH}"
ENV MANPATH="${MANPATH}:${NVCOMPILERS}/${NVARCH}/20.11/comm_libs/mpi/man"

# Install custom compile of boost - only necessary runtime components
RUN wget -O ~/boost_1_75_0.tar.bz2 -c 'https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2' --max-redirect=100 \
    && apt-get -y remove --purge libboost-all-dev \
    && cd ~ \
    && tar xjf ~/boost_1_75_0.tar.bz2 \
    && cd ~/boost_1_75_0/ \
    && ./bootstrap.sh --prefix=/usr/local --with-toolset=pgi  \
    && cp ~/boost_1_75_0/tools/build/example/user-config.jam ~/user-config.jam \
    && echo "using mpi : mpic++ ; " >> ~/user-config.jam \
    && cd ~/boost_1_75_0/tools/build \
    && ./bootstrap.sh && ./b2 install \
    && cd ~/boost_1_75_0 && b2 toolset=pgi --with-mpi --with-program_options --with-serialization stage install

# Install SuperLU5
RUN cd /opt/code \ 
    && curl -O -J -L https://github.com/xiaoyeli/superlu/archive/v5.2.1.tar.gz \
    && tar xvf superlu-5.2.1.tar.gz \
    && cd superlu-5.2.1 \
    && mkdir build \
    && cd build \
    && cmake ../ -DCMAKE_CXX_COMPILER=nvc++ -DCMAKE_C_COMPILER=nvc -DBUILD_SHARED_LIBS=ON \
    && make \
    && make install

# Install Armadillo
RUN cd opt/code \
    && git clone https://gitlab.com/conradsnicta/armadillo-code \
    && cd armadillo-code \
    && git checkout --track origin/9.900.x \
    && mkdir build \
    && cd build \
    && echo $PATH \
    && cmake ../ -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX_COMPILER=nvc++ -DCMAKE_C_COMPILER=nvc \
    && make \
    && make install \
    && ldconfig

# Install PowerGrid
RUN  cd /opt/code \
     && git clone https://github.com/mavel101/PowerGrid \
     && cd PowerGrid \
     && git checkout icefire \
     && mkdir build && cd build \
     && cmake ../ -DCMAKE_CXX_COMPILER=pgc++ \
     && make -j4 && make install

RUN ldconfig

# Expose all GPU to docker
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility